### PR TITLE
Playground sidepanel can be toggled with a button.

### PR DESCRIPTION
**Pull request by cristianvogel**
was referencing outside the containing folder

### CODE REVIEW

**Comment by cristianvogel** [comment]
Added a button to collapse the side pane of the playground, so editor can be full width. Made the default font a bit bigger.

**Comment by cristianvogel** [comment]
Ready for merge?

**Comment by cristianvogel** [comment]
Catching a few things in the user guide

**Comment by nick-thompson** [comment]
Thank you @cristianvogel, sorry for the delay!

**Pull request merged**
